### ISSUE TITLE
Conversion of NLTK tree to PTB format

### ISSUE THREAD

**Issue by anirudh708** [dmcc/PyStanfordDependencies#11]
The convert_tree() function is not able to form dependencies for a nltk tree and an alternate conversion from nltk to ptb doesnt work

[via http://stackoverflow.com/a/29614388/1118542]

**Comment by dmcc** [comment]
Thanks for the report. `convert_tree()` isn't designed to take NLTK `Tree` objects as arguments -- only strings of Penn Treebank trees (though it's easy to convert a `Tree` to this type of string with `str()`).

If you're using the Subprocess backend, there's a `debug=True` flag that you can pass to `convert_tree()` which may provide additional information.

If this doesn't help, please provide more details (ideally the whole sequence of PyStanfordDependencies related commands including which backend, version of SD, the string of the tree you want to convert, etc.).
