### ISSUE TITLE
Getting [Error 32] trying to parse tree from example

### ISSUE THREAD

**Issue by MisterMeUA** [dmcc/PyStanfordDependencies#15]
Hello, David.

I'm getting Windows [Error 32] error when I'm trying to parse tree from example.
Here is code:

sd = StanfordDependencies.get_instance(backend='subprocess')
sent = sd.convert_tree('(S1 (NP (DT some) (JJ blue) (NN moose)))')

Next error shows Visual Studio:
[Error 32] Ïðîöåñó íå âäàëîñÿ îòðèìàòè äîñòóï äî ôàéëó,: 'c:\users\sergiy\appdata\local\temp\tmpmd8c8k'
*file name differs all the time

**I've tried to use another constructor, using jar_filename parameter - same exception

***I've tried to install JPypeBackend - it didn't help. It started failing when I was trying to call get_instance method.

Maybe i'm doing something wrong, but if there is problem, pleace take a look.

Thanks a lot)

**Comment by dmcc** [comment]
Thanks for the report @MisterMeUA! Does Visual Studio show you the full stack trace?

Also, it looks like your error messages are in another encoding/language. Do you know what your specific error message is? ("Ïðîöåñó íå âäàëîñÿ îòðèìàòè äîñòóï äî ôàéëó") From what I can tell, Error 32 on Windows can be several things.

**Comment by MisterMeUA** [comment]
Yep, sorry about "error message". I got message about process cannto access to file.

**Comment by dmcc** [comment]
Thanks, that helps. Sounds like this might be related to #7 (which is strange since I thought #7 was closed). I'm afraid I won't be able to get to this for a couple weeks, but as a workaround, you might want to try replacing the `os.remove(input_file.name)` line (SubprocessBackend.py, line 80) with `pass`. This will result in the temporary files not getting deleted (not ideal), seems the better fix for Windows might be [here](http://stackoverflow.com/questions/1470350/why-is-the-windowserror-while-deleting-the-temporary-file).

**Comment by MisterMeUA** [comment]
Thanks for responce, but I cannot answer whether it helped for now.
I'll answer as soon as I try proposed workaround.

**Comment by MisterMeUA** [comment]
Using "pass" helped for me, and it did make everythong working)

Thanks, David, for your responce and help)

**Comment by ankurgulati** [comment]
Hi @dmcc , Even after replacing the os.remove(input_file.name) line (SubprocessBackend.py, line 80) with pass. I encountered the same error:

  Any help would be appreciated.

```
File "location\AppData\Local\Continuum\Anaconda2\lib\site-packages\StanfordDependencies\SubprocessBackend.py", line 87, in convert_trees
    pass
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'location\\appdata\\local\\temp\\tmpt1uijk'
```
