### ISSUE TITLE
CoNLL-X data format URL link not working

### ISSUE THREAD

**Issue by kaushikacharya** [dmcc/PyStanfordDependencies#26]
@dmcc 
URL mentioned in [class Token](https://github.com/dmcc/PyStanfordDependencies/blob/master/StanfordDependencies/CoNLL.py#L42) is no more available.

This could be updated with:
_CoNLL-X shared task on Multilingual Dependency Parsing by Buchholz and Marsi(2006)
http://aclweb.org/anthology/W06-2920
Section 3_

If you want, I can update.

**Comment by dmcc** [comment]
That would be great!
