### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by dmcc** [dmcc/PyStanfordDependencies#4]

**Comment by smartschat** [comment]
For a Python 3 project of mine I needed Stanford Dependencies and made your package Python 3 compatible. All unit tests pass under Python 2.7.3 and Python 3.3.5. How is the status of this issue, should I fork this repository and put my modifications online?

**Comment by dmcc** [comment]
Awesome! AFAIK, nobody else has worked on this issue and there's no major restructuring in progress, so this is a perfect time to check it in. Please fork and make a pull request.

By the way, I should say that IBM requires me have all contributors sign a contributor license agreement before merging changes:

        https://www.dropbox.com/s/woyyhxej4y0t2rw/cla-individual-PyStanfordDependencies.rtf?dl=1

Please email me if you have any questions about it (and apologies -- I've been meaning to add a `CONTRIBUTING.md` file with this information so potential contributors would know about it upfront. I'll add one later today).

**Comment by dmcc** [comment]
Added by @smartschat in https://github.com/dmcc/PyStanfordDependencies/pull/12.
